### ISSUE TITLE
Newer version of pydantic needed for python 3.11

### ISSUE THREAD

**Issue by slavisarad** [yezz123/fastapi-class#57]
When using fastapi-class with python 3.11 the following error ocurrs:

`  File "/usr/lib/python3.11/inspect.py", line 2721, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name` 

[This](https://github.com/tiangolo/fastapi/issues/5048) issue regarding this topic was reported for fastapi itself.

Seems like pydantic  >= v1.10.0a1 is needed, in order to solve that issue

**Comment by yezz123** [comment]
Thank you @slavisarad for reporting! It's fixed now ⭐
