### ISSUE TITLE
Recent fastapi support

### ISSUE THREAD

**Issue by luqasz** [yezz123/fastapi-class#84]
Hi.

Any chance to support newer versions of fastapi ?

**Comment by yezz123** [comment]
Hello 👋🏻 

you can check its already supported in the V3 but i can supported in the old version

**Comment by luqasz** [comment]
Ah you mean `feat/3` branch https://github.com/yezz123/fastapi-class/tree/feat/v3 ?

**Comment by yezz123** [comment]
> Ah you mean `feat/3` branch https://github.com/yezz123/fastapi-class/tree/feat/v3 ?

Yes i will finalize some stuff and release a new version 🙏🏻
